<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Form\Type\CarteType;
use AppBundle\Form\Type\InformationsType;
use AppBundle\Entity\User;
use AppBundle\Entity\Card;
use AppBundle\Service\FileUploader;

class GestionController extends Controller {

    /**
     * @Route("/gestion", name="gestion")
    */
    public function indexAction(Request $request, FileUploader $fileUploader) {

        $infoFormSuccess = false;
        $user = $this->getUser();

        $myCard = $this->getDoctrine()->getRepository('AppBundle:Card')->findBy(array('idUser' => $user->getId()));
        dump($myCard);

        $card = new Card;
        $carteForm = $this->createForm(CarteType::class);
        $carteForm->handleRequest($request);
        
        $infoForm = $this->createForm(InformationsType::class, $user);
        $infoForm->handleRequest($request);

        if ($infoForm->isSubmitted() && $infoForm->isValid()) {

             $data = $infoForm->getData();

             $file = $user->getAvatar();
             $fileName = $fileUploader->upload($file);

             $em = $this->getDoctrine()->getManager();

            //on recupére notre objet user
            //on le modifie
             $user->setAvatar($fileName);
             $user->setFirstName($data->getFirstName());
             $user->setLastName($data->getLastName());
             $user->setBirthday($data->getBirthday());
             $user->setBio($data->getBio());
             $em->persist($user);
             $em->flush();

             $infoFormSuccess = true;

        }

        if ($carteForm->isSubmitted() && $carteForm->isValid()) {

             $data = $carteForm->getData();

             $em = $this->getDoctrine()->getManager();

             $card->setName($data['titre']);
             $card->setCategory($data['type']);
             $card->setPrice($data['prix']);
             $card->setIdUser($user);
             
             $em->persist($card);
             $em->flush();

        }

     return $this->render('@App/gestion/gestion.html.twig', [
        'card' => $myCard,
        'infoFormSuccess' => $infoFormSuccess,
        'form' => $carteForm->createView(),
        'formInfo' => $infoForm->createView()
    ]);
 }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }



}
