<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use AppBundle\Form\Type\CarteType;
use AppBundle\Form\Type\InformationsType;
use AppBundle\Entity\User;
use AppBundle\Service\FileUploader;

class GestionController extends Controller {

    /**
     * @Route("/gestion", name="gestion")
    */
    public function indexAction(Request $request, FileUploader $fileUploader) {

        $carteForm = $this->createForm(CarteType::class);
        $carteForm->handleRequest($request);

        $user = new User();
        $infoForm = $this->createForm(InformationsType::class, $user);
        $infoForm->handleRequest($request);

        if ($infoForm->isSubmitted() && $infoForm->isValid()) {

           
           $data = $infoForm->getData();

//           dump($this->getUser()->getId());

       //    dump($data->getLastName(),$data->getFirstName(), $data->getAvatar()->getClientOriginalName());die;

           $file = $user->getAvatar();
           $fileName = $fileUploader->upload($file);


            $em = $this->getDoctrine()->getManager();

            $user = $this->getUser();
            $user->setAvatar($fileName);
            $user->setFirstName($data->getFirstName());
            $user->setLastName($data->getLastName());
            $user->setBirthday($data->getBirthday());
            $user->setBio($data->getBio());
            $em->persist($user);
            $em->flush();
            // return $this->redirectToRoute('task_success');
       }

       return $this->render('@App/gestion/gestion.html.twig', [
        'form' => $carteForm->createView(),
        'formInfo' => $infoForm->createView()
    ]);
   }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }



}
