services:
    peigneciseaux.security.authentication_handler:
        class: UserBundle\EventListener\LoginListener
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }